### ISSUE TITLE
Consider publishing this on clojars

### ISSUE THREAD

**Issue by mehdisadeghi** [hiposfer/gtfs.edn#1]
To make it publicly available :)

**Comment by carocad** [comment]
I have been thinking about it but I don't think having it in clojars would be that useful since there you only get the compiled Clojure files.

GTFS.edn however is mainly just data so a Java jar doesn't help much there.

However, I understand your point and I'm thinking of creating a library that exposes how we work with that data. I think that library should definitely be public :)

**Comment by carocad** [comment]
@mehdi I think I just understood your idea. Did you mean to put the code that I mentioned above directly in this repo and publish that?

I'm not sure which approach would be best though ....

**Comment by carocad** [comment]
After some thought I now think that your approach is the best solution since the dependency between the code using the data and the date itself is explicit and changes can be documented better that way
